// List Modfication
export const LIMIT_ACTION = "LIMIT_ACTION";
export const GO_TO_ACTION = "GO_TO_ACTION";
export const KEYWORD_SEARCH_ACTION = "KEYWORD_SEARCH_ACTION";
export const SEARCH_REQUEST_ACTION = "SEARCH_REQUEST_ACTION";
export const DATE_REQUEST_ACTION = "DATE_REQUEST_ACTION";
export const DATE_SUCCESS_ACTION = "DATE_SUCCESS_ACTION";

// Order List
export const LIST_ORDER_SUCCUESS = "LIST_ORDER_SUCCESS";
